ruthlesspa/ruthlesspa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='core'),
    path('expensestracker/', include('expensestracker.urls')),
    path('caloriestracker/', include('caloriestracker.urls')),
    path('api/user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ruthlesspa/user/urls.py
from django.urls import path

from user import views


app_name = 'user'

urlpatterns = [
    path('create/', views.CreateUserView.createInactive, name='create'),
    path('login/', views.CreateUserView.login, name='login'),
    path('logout/', views.CreateUserView.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.CreateUserView.activate, name='activate'),
]

ruthlesspa/templates/partials/loginform/loginform.html
{% block content %}

  <form class="card2" action="{% url 'user:create' %}" method="POST" name="myForm">
    <label>
      <p class="label-txt">ENTER YOUR EMAIL</p>
      <input type="text" class="datepickerInput" name="email" autocomplete="email" required>
      <div class="line-box">
        <div class="line"></div>
      </div>
    </label>
    <label>
      <p class="label-txt">ENTER YOUR PASSWORD</p>
      <input type="password" class="datepickerInput" autocomplete="current-password" name="password" required>
      <div class="line-box">
        <div class="line"></div>
      </div>
    </label>
    <button class="btn-secondary" type="submit">register</button>

  </form>

  {% endblock %}