ruthlesspa/ruthlesspa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='core'),
    path('expensestracker/', include('expensestracker.urls')),
    path('caloriestracker/', include('caloriestracker.urls')),
    path('api/user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ruthlesspa/user/urls.py
from django.urls import path

from user import views


app_name = 'user'

urlpatterns = [
    path('create/', views.CreateUserView.createInactive, name='create'),
    path('login/', views.CreateUserView.login, name='login'),
    path('logout/', views.CreateUserView.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.CreateUserView.activate, name='activate'),
]

ruthlesspa/templates/core/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}  
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

ruthlesspa/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ruthless Personal Assistant</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="{% static 'loginform.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    {% if user.is_authenticated %}
        <form action="{% url 'user:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" id="logout">Logout
            </button>
        </form>
    {% endif %}
    <div class="logregist">
        {% include 'partials/loginform/loginform.html' %}
        {% include 'partials/registerform.html' %}
    </div>
    <h1 class="mainTitleH1">Daily improvement motivation</h1>
    <div class="container">
        <a href="{% url 'caloriestracker' %}" class="mainBtn" >Calories tracker
            <div id="caloriestrackerBtn">
            </div>
        </a>

        <a href="pomodoros.html" class="mainBtn" id="middleBtn">Pomodoro Tracker
            <div id="pomodorosBtn">
            </div>
        </a>

        <a href="{% url 'expensestracker' %}" class="mainBtn">Expenses tracker
            <div id="expensestrackerBtn">
            </div></a>
    </div>

    

    <script src="{% static 'loginform.js' %}"></script>
    <script src="{% static 'main.js' %}"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>