ruthlesspa/ruthlesspa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='core'),
    path('expensestracker/', include('expensestracker.urls')),
    path('caloriestracker/', include('caloriestracker.urls')),
    path('api/user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ruthlesspa/user/urls.py
from django.urls import path

from user import views


app_name = 'user'

urlpatterns = [
    path('create/', views.CreateUserView.createInactive, name='create'),
    path('login/', views.CreateUserView.login, name='login'),
    path('logout/', views.CreateUserView.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.CreateUserView.activate, name='activate'),
]

ruthlesspa/templates/partials/_alerts.html
{% if messages %}

    {%for message in messages %}
        <div class="alertContainer" id="message">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">
                    &times;
                </span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags|title }}
                    {%endif %}
                </strong>
                {{message}}
            </div>
        </div>

    {% endfor %}

{% endif %}

ruthlesspa/templates/partials/mealCard.html
<div id="mealCard" class="card text-white bg-warning mb-3" style="max-width: 18rem;">
    <div class="card-header">
        <h4 class="meal-number">Meal 1</h4>
        <h5 class="card-title">Breakfast</h5>
    </div>
    <div class="card-body cardFlexContainer">
        <p class="card-text-name">Egg</p>
        <p class="card-text-calories">55kcal</p>
        <button class="btn-outline-danger btn-sm remove-meal"
        id="removeMealCard">X</button>
    </div>
    <div class="card-body-add-position">
        <button class="btn-success btn-sm" id="add-meal-button">Add a meal</button>
    </div>
</div>

ruthlesspa/templates/partials/registerform.html
{% block content %}

    <form class="card2" action="{% url 'user:login' %}" method="POST">
        {% csrf_token %}
        <label>
            <p class="label-txt">ENTER YOUR EMAIL</p>
            <input type="text" class="datepickerInput" name="email" autocomplete="email" required>
            <div class="line-box">
                <div class="line"></div>
            </div>
            </label>
            <label>
            <p class="label-txt">ENTER YOUR PASSWORD</p>
            <input type="password" class="datepickerInput" name="password" autocomplete="current-password" required>
            <div class="line-box">
                <div class="line"></div>
            </div>
            </label>

            <button class="btn-secondary" type="submit">Login</button>
    </form>

{% endblock %}